#!/usr/bin/env bash
#
# Stop local monitoring stack.

set -o errexit
set -o pipefail
set -o nounset

# shellcheck disable=SC1091
source utils.sh

check_command docker

fancy_echo "Stopping local monitoring stack"
docker compose --file compose.monitoring.yaml stop
